#:include frontend/OpenScreen.kv
#:include frontend/MusicianSignup.kv
#:include frontend/MainScreen.kv
#:include frontend/SearchScreen.kv
#:include frontend/AppDefaults.kv


WindowManager:
    canvas.before:
        Color:
            rgba: (245/255,222/255,179/255,1)
        Rectangle:
            size:self.size
            pos:self.pos
    MainScreen:
    OpenScreen:
    MusicianSignup:
    SearchScreen:
    

